import Link from "next/link";

export const metadata = { title: "Protocol docs" };
const splits = [
  ["Creator", "Direct claimable allocation"], ["Parent holders", "Merkle reward deposit"], ["Ancestors", "Up to three levels with decay"],
  ["Burn", "Transferred to dead address"], ["Liquidity", "Returned to the active market"], ["Pad owner", "Direct claimable allocation"], ["Protocol", "Treasury allocation"]
];
export default function DocsPage() {
  return <div className="docs-layout content-width"><aside className="docs-nav"><span className="eyebrow">Documentation</span><a href="#model">Model</a><a href="#verification">Verification</a><a href="#fees">Fee routing</a><a href="#safety">Safety</a><a href="#states">Data states</a></aside><article className="docs-copy"><span className="eyebrow">Protocol primer</span><h1>How Canopy works</h1><p className="lede">Canopy is a separate companion protocol. It verifies pons roots, then creates recursive markets whose quote asset is always the direct parent token.</p><section id="model"><h2>Recursive market model</h2><p>A pons v2 token can become a depth-zero Canopy pad only when the official factory reports that it exists, and only its original deployer may open it. A Canopy child may open the next pad only through its recorded creator. Depth is capped at sixteen.</p><pre><code>pons token → Canopy pad → child / parent market → child pad → …</code></pre></section><section id="verification"><h2>What is—and is not—verified</h2><p>The root check reads <code>getLaunchedToken</code> from the documented pons v2 factory. Pons supports owner-approved quote assets; that does not mean arbitrary parents are approved. Canopy therefore never represents a nested market as a pons market.</p><div className="callout"><strong>Boundary</strong><p>Pons trades follow pons economics. Only trades executed through a Canopy child market produce Canopy routing and reward events.</p></div></section><section id="fees"><h2>Versioned fee routing</h2><p>Every pad pins an immutable fee-config version when it opens. Allocation basis points must sum to 10,000.</p><div className="docs-table">{splits.map(([name, route]) => <div key={name}><strong>{name}</strong><span>{route}</span></div>)}</div></section><section id="safety"><h2>Safety model</h2><ul><li>Global emergency pause gates state-changing protocol actions.</li><li>Markets reject fee-on-transfer behavior using exact balance checks.</li><li>Trades include a caller-provided minimum output and deadline.</li><li>Rewards use pull claims and Merkle proofs, avoiding holder loops.</li><li>Cross-market routes are atomic and limited to four hops.</li></ul><p>This implementation is pre-audit. It is not suitable for mainnet deployment.</p></section><section id="states"><h2>Honest data states</h2><p><code>live</code> means the response came from a current RPC or indexed canonical event. <code>not_indexed</code> means no relevant record exists yet. <code>not_available</code> indicates a failed or absent dependency. <code>integration_not_verified</code> means a Canopy contract address has not been deployed and bytecode-checked.</p><Link className="text-link" href="/status">Inspect current system state →</Link></section></article></div>;
}
